codecov:
  strict_yaml_branch: main
coverage:
  range: [80, 100]
  parsers:
    javascript:
      enable_partials: true
  status:
    patch:
      informational: true
    project:
      informational: true
comment: false
