import { promises as fs } from 'fs'
import process from 'process'
import { fileURLToPath } from 'url'

import glob from 'fast-glob'

const FRAMEWORKS_DIR = new URL('../src/frameworks/', import.meta.url)
const BUILD_DIR = new URL('../src/generated/', import.meta.url)
const FRAMEWORKS_BUILD = new URL('frameworks.ts', BUILD_DIR)

// We enforce frameworks to be written with JSON to ensure they remain logicless
// which is simpler for contributors and avoid adding unnecessary logic.
// However, Node.js does not support JSON imports without any experimental
// flags. Also, not all browsers support it unless Webpack preprocesses it.
// Therefore, we transform JSON to JavaScript files using at build time.
const transformFrameworks = async function () {
  await fs.mkdir(BUILD_DIR, { recursive: true })
  const frameworkFiles = await glob('*.json', { cwd: fileURLToPath(FRAMEWORKS_DIR), absolute: true })
  const frameworks = await Promise.all(frameworkFiles.map(transformFramework))
  const fileContents = `${FRAMEWORKS_HEADER}${JSON.stringify(frameworks, null, 2)}`
  await fs.writeFile(FRAMEWORKS_BUILD, fileContents)
}

const updateLogoUrls = function (contents) {
  const updatedContents = contents
  const originalLogo = contents.logo
  if (originalLogo) {
    for (const [theme, urlPath] of Object.entries(originalLogo)) {
      updatedContents.logo[theme] = (process.env.DEPLOY_PRIME_URL || 'https://framework-info.netlify.app') + urlPath
    }
  }

  return updatedContents
}

const transformFramework = async function (frameworkFile) {
  const jsonContents = await fs.readFile(frameworkFile)
  const contents = JSON.parse(jsonContents)

  const updatedContents = updateLogoUrls(contents)
  return updatedContents
}

const FRAMEWORKS_HEADER = `import type { FrameworkDefinition } from "../types.js"
// This file is autogenerated at build time
export const FRAMEWORKS: FrameworkDefinition[] = `

transformFrameworks()
