import { join } from 'path'

import { beforeEach, describe, expect, test } from 'vitest'

import { mockFileSystem } from '../../tests/mock-file-system.js'
import { NodeFS } from '../node/file-system.js'
import { Project } from '../project.js'

beforeEach((ctx) => {
  ctx.fs = new NodeFS()
})

const NPM_LOCKFILE = JSON.stringify({
  name: 'fixture',
  version: '1.0.0',
  lockfileVersion: 3,
  requires: true,
  packages: {
    '': { name: 'fixture', version: '1.0.0', devDependencies: { 'vite-plus': '^0.2.0' } },
    'node_modules/vite-plus': {
      version: '0.2.4',
      resolved: 'https://registry.npmjs.org/vite-plus/-/vite-plus-0.2.4.tgz',
      integrity: 'sha512-fixture',
    },
  },
})

const PNPM_LOCKFILE = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    devDependencies:
      vite-plus:
        specifier: ^0.2.0
        version: 0.2.4

packages:

  vite-plus@0.2.4:
    resolution: {integrity: sha512-fixture}
`

const YARN_LOCKFILE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


vite-plus@^0.2.0:
  version "0.2.4"
  resolved "https://registry.yarnpkg.com/vite-plus/-/vite-plus-0.2.4.tgz#fixture"
  integrity sha512-fixture
`

test('detects vite-plus via a devDependency and reports the declared version without a lock file', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({ devDependencies: { 'vite-plus': '^0.2.0' } }),
  })
  const detected = await new Project(fs, cwd).detectBuildSystem()

  expect(detected[0]?.id).toBe('vite-plus')
  expect(detected[0]?.name).toBe('Vite Plus')
  expect(detected[0]?.version).toBe('^0.2.0')
})

test('detects vite-plus via a regular dependency', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({ dependencies: { 'vite-plus': '0.2.4' } }),
  })
  const detected = await new Project(fs, cwd).detectBuildSystem()

  expect(detected[0]?.id).toBe('vite-plus')
  expect(detected[0]?.version).toBe('0.2.4')
})

test('does not detect vite-plus without the dependency', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({ devDependencies: { vite: '^6.0.0' } }),
  })
  const detected = await new Project(fs, cwd).detectBuildSystem()

  expect(detected.find(({ id }) => id === 'vite-plus')).toBeUndefined()
})

describe.each([
  { lockfileName: 'package-lock.json', lockfileContents: NPM_LOCKFILE },
  { lockfileName: 'pnpm-lock.yaml', lockfileContents: PNPM_LOCKFILE },
  { lockfileName: 'yarn.lock', lockfileContents: YARN_LOCKFILE },
])('with a $lockfileName lock file', ({ lockfileName, lockfileContents }) => {
  test('resolves the locked version', async ({ fs }) => {
    const cwd = mockFileSystem({
      'package.json': JSON.stringify({ devDependencies: { 'vite-plus': '^0.2.0' } }),
      [lockfileName]: lockfileContents,
    })
    const detected = await new Project(fs, cwd).detectBuildSystem()

    expect(detected[0]?.id).toBe('vite-plus')
    expect(detected[0]?.version).toBe('0.2.4')
  })
})

test('detects vite-plus from a monorepo base directory with the dependency at the root', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({
      workspaces: ['apps/*'],
      devDependencies: { 'vite-plus': '^0.2.0' },
    }),
    'package-lock.json': NPM_LOCKFILE,
    'apps/web/package.json': JSON.stringify({ name: 'web' }),
  })
  const detected = await new Project(fs, join(cwd, 'apps/web'), cwd).detectBuildSystem()

  const vitePlus = detected.find(({ id }) => id === 'vite-plus')
  expect(vitePlus?.version).toBe('0.2.4')
})

test('resolves against the lock file of the package.json with vite-plus dep', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({
      workspaces: ['apps/*'],
      devDependencies: { 'vite-plus': '^0.2.0' },
    }),
    'package-lock.json': NPM_LOCKFILE,
    'apps/web/package.json': JSON.stringify({ name: 'web' }),
    // stray nested lock file that does not lock the root's dependencies
    'apps/web/package-lock.json': JSON.stringify({
      name: 'web',
      version: '1.0.0',
      lockfileVersion: 3,
      requires: true,
      packages: {
        '': { name: 'web', version: '1.0.0' },
      },
    }),
  })
  const detected = await new Project(fs, join(cwd, 'apps/web'), cwd).detectBuildSystem()

  const vitePlus = detected.find(({ id }) => id === 'vite-plus')
  expect(vitePlus?.version).toBe('0.2.4')
})

test('provides vp run workspace commands for a package', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({ workspaces: ['apps/*'], devDependencies: { 'vite-plus': '^0.2.0' } }),
    'apps/web/package.json': JSON.stringify({
      name: 'web',
      scripts: { dev: 'vite', build: 'vite build', lint: 'oxlint' },
    }),
  })
  const [vitePlus] = await new Project(fs, cwd).detectBuildSystem()

  expect(vitePlus.id).toBe('vite-plus')
  expect(await vitePlus.getCommands('apps/web')).toEqual([
    { type: 'dev', command: 'vp run --filter web dev' },
    { type: 'build', command: 'vp run --filter web build' },
    { type: 'unknown', command: 'vp run --filter web lint' },
  ])
})

test('returns no commands for a package without a name', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({ workspaces: ['apps/*'], devDependencies: { 'vite-plus': '^0.2.0' } }),
    'apps/web/package.json': JSON.stringify({ scripts: { build: 'vite build' } }),
  })
  const [vitePlus] = await new Project(fs, cwd).detectBuildSystem()

  expect(await vitePlus.getCommands('apps/web')).toEqual([])
})

test('falls back to the declared version when the lock file does not contain the package', async ({ fs }) => {
  const cwd = mockFileSystem({
    'package.json': JSON.stringify({ devDependencies: { 'vite-plus': '^0.2.0' } }),
    'package-lock.json': JSON.stringify({
      name: 'fixture',
      version: '1.0.0',
      lockfileVersion: 3,
      requires: true,
      packages: {
        '': { name: 'fixture', version: '1.0.0' },
      },
    }),
  })
  const detected = await new Project(fs, cwd).detectBuildSystem()

  expect(detected[0]?.id).toBe('vite-plus')
  expect(detected[0]?.version).toBe('^0.2.0')
})
