name: Netlify E2E Tests

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - name: Install Netlify E2E
        run: npm install -g @netlify/e2e@1.0.0-rc.1
      - name: Create Remlink Config
        run: node ./tools/create-remlink.config.js
      - name: Trigger Netlify E2E image build
        id: extract-deploy-id
        run: |
          output=$(netlify-e2e build-image ./remlink.config.json)
          echo "pipelineId=$(echo "output" | jq -r '.pipelineId')" >> $GITHUB_ENV
          echo "testImageTag=$(echo "output" | jq -r '.tag')" >> $GITHUB_ENV

      - name: Echo extracted values
        run: |
          echo "The extracted pipelineId is: ${{ env.pipelineId }}"
          echo "The extracted Tag is: ${{ env.testImageTag }}"
