name: 'Mark and close stale issues in the repo'
on:
  schedule:
    - cron: '00 14 * * *' # runs daily at 14:00 https://crontab.guru/#00_14_*_*_*

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3.0.19
        with:
          exempt-issue-labels: 'WIP,security,action_item,never_stale'
          days-before-issue-stale: 365
          stale-issue-label: 'stale'
          stale-issue-message:
            'This issue has been automatically marked as stale because it has not had activity in 1 year. It will be
            closed in 14 days if no further activity occurs. Thanks!'
          days-before-issue-close: 14
          close-issue-message: 'This issue was closed because it had no activity for over 1 year.'
          days-before-pr-close: -1
